### ISSUE TITLE
Feat: keyboard shortcuts just to go to the next diff file

### ISSUE THREAD

**Issue by huyz** [alfredbirk/go-to-next-change#1]
I already have my own keyboard shortcut for navigating changes within the same file.
I would like to have a separate keyboard shortcut for navigating to the next diff file or previous file, regardless of my cursor's current position.
Could you add separate commands?

**Comment by alfredbirk** [comment]
Good idea, I have now added these in v0.3.0:
- Go to next changed file
- Go to previous changed file

**Comment by huyz** [comment]
Thanks!
