### ISSUE TITLE
Shortcuts don't do anything on my machine

### ISSUE THREAD

**Issue by CombeeMike** [alfredbirk/go-to-next-change#2]
When pressing `Alt+l`, I'm only seeing the following in my VSCode task bar and nothing else happens:

![image](https://github.com/alfredbirk/go-to-next-change/assets/30658772/0f8ffc71-00d1-40f6-9288-3a10b7acfb71)

When pressing `Alt+k`, nothing happens at all 🤷‍♂️

I usually start chords with `Ctrl+k`. I don't know how `Alt+l` is also connected to chords and whether I can somehow customize this in VSCode settings etc.

In the keybindings, I only see the following for `Alt+l` of which none seems to interfere with your plugin (I guess):

![image](https://github.com/alfredbirk/go-to-next-change/assets/30658772/c9c6292b-1d33-4796-91bf-774e4aa3fd85)

# Env

I'm on Win 10, VSCode `1.83.1`.

Details copied from VSCode's version dialog:
```
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by CombeeMike** [comment]
# Update

I just removed the 2 keybindings for the `Live server` shown in the screenshot above. `Alt+l` is now don't showing the "Waiting for chord" message anymore, but simply does nothing at all like `Alt+k`.

**Comment by alfredbirk** [comment]
Hmm, okay. I will consider changing the default shortcuts. I think opt shortcuts on mac are in general a bit flaky. Open to suggestions for what the default should be.

**Comment by CombeeMike** [comment]
> I think opt shortcuts on mac are in general a bit flaky.

Really, how so? Custom shortcuts from plugins seem like a well established mechanism in VSCode to me especially since it provides rather straight forward API for extension development for it.

Asking just out of interest since I have no hands on experience with VSCode on Mac.

> Open to suggestions for what the default should be.

I really don't want to contribute anything here as preferred shortcuts are a rather personal thing which depend on multiple factors like operating system, other installed plugins etc.

I personally used `Shift+Ctrl+Alt+n` for "go to next" til now (with the `runCommand` as basically described [here](https://stackoverflow.com/a/76485588/1273551)) since it is relatively easy to type on a Win keyboard and "rare" enough to not collide with other shortcuts but I know that this is very clumsy & don't think that it should be the default for an extension...

**Comment by CombeeMike** [comment]
Obsolete. Default keybindings were not set somehow but setting custom ones solved the issue for me.
Also see [this ticket](https://github.com/alfredbirk/go-to-next-change/issues/3).
