### ISSUE TITLE
Feat: Allow customization of shortcuts

### ISSUE THREAD

**Issue by CombeeMike** [alfredbirk/go-to-next-change#3]
I don't see no option to change the current shortcuts `Alt+l` & `Alt+k` to something different in the keybindings editor. I find some results for "go to next change" etc. but they all look like built in VSCode actions or from other extensions but nothing from this extension:

![image](https://github.com/alfredbirk/go-to-next-change/assets/30658772/c7c17826-b6ab-4c4e-b3cd-036b3ce3b929)

Am I right in assuming that those shortcuts are not customizable ATM? If so, please add an option to make them customizable.

A bit related to my earlier [bug report](https://github.com/alfredbirk/go-to-next-change/issues/2) as different shortcuts might work on my machine (just a wild guess).

**Comment by alfredbirk** [comment]
They are customisable, the commands are the two on the bottom: "Go to next git change" and "Go to previous git change". Not sure why the keybindings are blank, it might be related to the shortcuts not working.

(I updated the command names in readme now to make it correct)

**Comment by CombeeMike** [comment]
I have no idea how I was able to not see those 🙈
FYI, with correctly set keybindings, the extension seems to be doing what it's supposed to do, so [this other issue](https://github.com/alfredbirk/go-to-next-change/issues/2) I reported is obsolete.

Sorry for not seeing this 🤦‍♂️
