### ISSUE TITLE
Bug: support Tree view

### ISSUE THREAD

**Issue by huyz** [alfredbirk/go-to-next-change#4]
It seems that this was designed for when the Source Control pane lists files as a List. I happen to use `View as Tree`. This means that often, when going to the next file, the selection ends on a folder rather than the next file in the next folder.

**Comment by alfredbirk** [comment]
I made some changes, so it should work with tree view now - let me know.

**Comment by huyz** [comment]
Thanks for the quick attempt.  There are still some issues but I'm trying to figure them out

**Comment by alfredbirk** [comment]
Alright, just let me know if you want me to look into it!
