### ISSUE TITLE
Bug: Cannot cycle through files in Win11

### ISSUE THREAD

**Issue by surfinzap** [alfredbirk/go-to-next-change#6]
When I cycle through the changes and the next change is in the next file (or in the same file at the beginning), I get the following error:
`
cannot open file:///e%253A/folder/structure/file.json. Detail: Unable to read file '\e%3A\folder\structure\file.json' (Error: Unable to resolve nonexistent file '\e%3A\folder\structure\file.json')
`

VS Code 1.84.2, Win 11

**Comment by alfredbirk** [comment]
I made some changes and got it working on my old Windows PC ✅ Can you confirm the new version works?

**Comment by surfinzap** [comment]
hey @alfredbirk it works now, thanks for the update!
