### ISSUE TITLE
Update the doc for Mac users

### ISSUE THREAD

**Issue by iswarmondal** [alfredbirk/go-to-next-change#7]
As of the current readme file, it shows instruction only for windows and Linux key bindings (`alt`).

Can we update the doc so that is also shows the key bindings for mac users (`option`)?

![Screenshot 2023-11-22 at 10 46 55 AM](https://github.com/alfredbirk/go-to-next-change/assets/73457704/f48f20ae-b487-4250-aa22-3138a6b14f9c)

**Comment by alfredbirk** [comment]
Done, thanks! ✅
