### ISSUE TITLE
Support for multiple repos

### ISSUE THREAD

**Issue by TheFlux7** [alfredbirk/go-to-next-change#9]
This extension seems really nice, but it currently supports only one repo, namely the first listed by the `git` extension. (sadly the first repo in my case isn't my "main" one...):

```typescript
    const repos = git.repositories;
    const isTreeView = vscode.workspace.getConfiguration("go-to-next-change").get("treeView");

    const changedFiles = await repos[0].state.workingTreeChanges
```

It would be nice if we could scroll between files starting from the currently active repository. Maybe then scroll over the repositories, or stay in the same repository.

Cheers!

**Comment by alfredbirk** [comment]
Hey, good suggestion! I published a new version which should hopefully solve this. Can you confirm whether or not it works?

**Comment by TheFlux7** [comment]
Thank you for acting so fast!!

Yes, this works on my end, I can scroll through the main repo.

Let me see if I find time to open a PR with other improvements. I think it would be great if we can detect in which repository the actively selected file belongs, and then scroll over the changed files of this repo.

**Comment by alfredbirk** [comment]
Nice, feel free to open PR with suggestions 👍  Keep in mind that the user might not have any files open, so would at least need a fallback with that solution I believe.
